### ISSUE TITLE
translateX does not work on Android

### ISSUE THREAD

**Issue by kaioduarte** [catalinmiron/react-native-dot-inversion#1]
Hi Catalin,

First of all, thank you for making such amazing videos!

I ran the app on Expo and it crashes on Android, because `translateX` does not accept string as value and by checking the docs, it shouldn't work also on iOS, but it works ¯\_(ツ)_/¯.

<img src="https://user-images.githubusercontent.com/11046907/89306806-458c8000-d668-11ea-92fa-622eb8a62b21.jpg" width="30%" height="30%">

Is there any workaround for that? Thanks

**Comment by dnovacik** [comment]
well you can still use values there (since the element has both width and height set to 100px you can input values:

`
translateX: bgColorAnimatedValue.interpolate({
  inputRange: [0, 0.5, 1],
  outputRange: [0, 50, 0]
})
`
